services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_NAME=${DB_NAME:-todoapp}
    env_file:
      - .env.docker
    restart: always

  db:
    container_name: db
    tty: true
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${DB_NAME:-todoapp}
      - DB_HOST=db  
    image: postgres:alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always